### ISSUE TITLE
Fix Reader URL Link Immediately After Assigning Section

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#117] opened 2021-04-07 23:30 UTC
When in a section compiler, assign a section to a reader. The reader's name appears for that section.

The URL on the link for the reader's name has square brackets around the reader ID, so that the URL is invalid.
Example: https://librivox.org/reader/[6399]

This gets cleared and corrected when one refreshes the web page.

Is there a way to remove those square brackets, to the URL is valid right away?

**Comment by ITD88** [comment] 2021-11-22 06:25
The brackets are being added [here](https://github.com/LibriVox/librivox-catalog/blob/master/public_html/js/private/section_compiler/index.js#L277) (It's an array turned into a string) and it's being passed with the brackets into this [where it becomes a URL](https://github.com/LibriVox/librivox-catalog/blob/master/public_html/js/private/section_compiler/index.js#L515). Could this be fixed by just stripping the first and last characters of reader_id? That seems like the safest way to fix it without breaking something else.

**Comment by kgroeneveld** [comment] 2022-01-08 16:37
>Could this be fixed by just stripping the first and last characters of reader_id? That seems like the safest way to fix it without breaking something else.

That would work. But it seems more like fixing the symptom than the cause. Which would probably be safer, but messier in the long run. I just submitted a PR with an alternate fix which also seems straightforward enough.

**Closed** 2022-01-09 19:48 UTC
